@echo off
echo.
echo.
echo Please wait.....Starting the program.....
echo.
echo [IF YOU ENTER ANY KEY THE PROGRAM WILL START AUTOMATICALLY]
echo.
echo.
pause


echo Title: Novel Smart Algae Bio Panel and It's Growth Forecasting using ML - A Sustainable Solution
echo.
echo This program is created by Mr. Shreyash A. Kamble.
echo For inquiries, please contact: shreyash261020@gmail.com
echo GitHub : https://github.com/mrkshreyash
echo.
echo The program is available for public use with due credit to the author.

echo.
echo.

pip install -r requirements.txt

echo.
echo. 

streamlit run Smart_Algae_Growth_Forecasting.py